### ISSUE TITLE
Can't download and que after search a karaoke song

### ISSUE THREAD

**Issue by rufo28** [vicwomg/pikaraoke#260]

**Comment by rufo28** [comment]
i'm using the raspberry pi 4, and i directly install using the pi image. installation successfull, then updating sudo apt upgrade last reboot.
Excited to try and search for song but after selecting song to download, it didn't download or put in a que.
It was not even in the folder to browse.

**Comment by vicwomg** [comment]
Upgrade pikaraoke

Log in to the pi,
Run: cd ~/pikaraoke
Run: git pull
Restart

Upgrade yt-dl

Go to the pikaraoke web interface
Go to the settings area and click the link to upgrade yt-dl

That should fix it

-v

**Comment by rufo28** [comment]
Just to add , after the given script. i still facing the issue.
the DL version in in latest one.

Any other solution? 
Thanks in advance

**Comment by vicwomg** [comment]
Can't think of anything else. It's possible YouTube has disabled the auth
keys and yt-dl hasn't caught up with a fix.

The output of /var/log/pikaraoke.log while trying to download might tell us
something if you can access it

**Comment by musicaltank** [comment]
@rufo28 - Take a look at my thread in Discussions. Your issue sounds very similar to (if not exactly like) mine. In the end, I was able to update yt-dlp by logging into the pi and running the following code provided by @vicwomg:

sudo pip3 install yt-dlp -U

**Comment by rufo28** [comment]
> /var/log/pikaraoke.log

Below the log after downloading one song.

![image](https://github.com/vicwomg/pikaraoke/assets/53016920/67d50988-ec94-4df0-bf09-ff3eec0473b0)

**Comment by rufo28** [comment]
> @rufo28 - Take a look at my thread in Discussions. Your issue sounds very similar to (if not exactly like) mine. In the end, I was able to update yt-dlp by logging into the pi and running the following code provided by @vicwomg:
> 
> sudo pip3 install yt-dlp -U

thanks for the feedback...
already updated but issue still persist.

![image](https://github.com/vicwomg/pikaraoke/assets/53016920/d1b7cccb-3865-4a3e-8dfe-215dd414bcf1)

**Comment by musicaltank** [comment]
> thanks for the feedback...
> already updated but issue still persist.

Well shucks - sorry, wish I could help more.

**Comment by alastairbdoggett** [comment]
i am also running into this issue. has anyone been able to confirm if it is a breaking change from YouTube? or is there a workaround here

**Comment by alastairbdoggett** [comment]
update: i am still seeing download and search result issues. any ideas what could be causing this instability?

**Comment by rufo28** [comment]
everyone got any ideas, still have issue in downloading songs

**Comment by vicwomg** [comment]
> everyone got any ideas, still have issue in downloading songs

I think that the issue here is that you have multiple yt-dlp versions installed. You can check with `sudo find / -name yt-dlp` if you see multiple versions, you'll need to remove them all, then reinstall with `sudo pip3 install yt-dlp -U`

**Comment by vicwomg** [comment]
This should no longer an issue in the latest pikaraoke 1.3, which isolates yt-dlp to venv
